# Measure the similarity between the clusters generated by two different
# algorithms. Uses Jaccard's Similarity Coefficient to find the similarity
# of each combination of clusters, then uess a similarity metric to determine
# how alike the clusters are.

library(kernlab)
# First, find the clusters using each method.
data = read.table(argvs[1], row.names = 1)
kM = kmeans(data, centers = 3)
cp = specc(data, centers = 3)

# Create the cluster sets.
seqNames = row.names(data)
kClusters = kM$cluster
kC1 = seqNames[which(kCluster==1)]
kC2 = seqNames[which(kCluster==2)]
kC3 = seqNames[which(kCluster==3)]
